auto-buy-feature:
  enabled: true
  discord_logging_channel_id: "1268264904888942635"
  price_threshold_percentage: 20
  max_players_to_buy_from: 30
  max_money_to_spend_per_player: 300
  max_amount_to_buy_per_player: 64
  prices:
    ACACIA_LOG:
      - 0.20
    ALLIUM:
      - 0.74
    AMETHYST_BLOCK:
      - 0.16
    AMETHYST_CLUSTER:
      - 1.95
    AMETHYST_SHARD:
      - 0.43
    ANCIENT_DEBRIS:
      - 78.93
    ANDESITE:
      - 0.02
    APPLE:
      - 0.39
    ARMADILLO_SCUTE:
      - 0.01
    ARMOR_STAND:
      - 10.0
    ARROW:
      - 0.14
    AZALEA:
      - 1.45
    AZALEA_LEAVES:
      - 0.1
    AZURE_BLUET:
      - 2.0
    BAKED_POTATO:
      - 0.5
    BAMBOO:
      - 0.04
    BAMBOO_BLOCK:
      - 0.31
    BASALT:
      - 0.72
    BEACON:
      - 119.91
    BEEF:
      - 2.04
    BEETROOT:
      - 2.1
    BELL:
      - 37.5
    BIG_DRIPLEAF:
      - 0.7
    BIRCH_LOG:
      - 0.44
    BLACKSTONE:
      - 0.17
    BLACK_BANNER:
      - 50.0
    BLACK_CARPET:
      - 0.3
    BLACK_CONCRETE:
      - 0.74
    BLACK_DYE:
      - 0.5
    BLACK_TERRACOTTA:
      - 2.72
    BLACK_WOOL:
      - 0.32
    BLAZE_POWDER:
      - 0.85
    BLAZE_ROD:
      - 2.15
    BLUE_BANNER:
      - 20.0
    BLUE_CONCRETE:
      - 1.5
    BLUE_DYE:
      - 1.24
    BLUE_ICE:
      - 2.96
    BLUE_ORCHID:
      - 2.5
    BLUE_STAINED_GLASS:
      - 0.25
    BLUE_TERRACOTTA:
      - 2.02
    BLUE_WOOL:
      - 0.05
    BOLT_ARMOR_TRIM_SMITHING_TEMPLATE:
      - 54.2
    BONE:
      - 0.11
    BONE_BLOCK:
      - 3.54
    BONE_MEAL:
      - 0.16
    BOOK:
      - 0.96
    BOOKSHELF:
      - 10.36
    BOW:
      - 0.3
    BRAIN_CORAL_BLOCK:
      - 7.0
    BRAIN_CORAL_FAN:
      - 0.75
    BREAD:
      - 0.41
    BREEZE_ROD:
      - 1.06
    BRICKS:
      - 0.68
    BROWN_CONCRETE:
      - 1.5
    BROWN_DYE:
      - 0.25
    BROWN_MUSHROOM:
      - 0.76
    BROWN_MUSHROOM_BLOCK:
      - 0.1
    BROWN_TERRACOTTA:
      - 2.3
    BROWN_WOOL:
      - 0.09
    BUBBLE_CORAL:
      - 3.15
    CACTUS:
      - 0.02
    CAKE:
      - 3.0
    CALCITE:
      - 0.04
    CAMPFIRE:
      - 10.0
    CANDLE:
      - 0.6
    CARROT:
      - 0.09
    CHAINMAIL_BOOTS:
      - 270.0
    CHAINMAIL_CHESTPLATE:
      - 295.0
    CHAINMAIL_LEGGINGS:
      - 285.0
    CHERRY_LEAVES:
      - 0.06
    CHERRY_LOG:
      - 0.36
    CHERRY_PLANKS:
      - 0.23
    CHERRY_SAPLING:
      - 2.38
    CHEST:
      - 1.0
    CHORUS_FRUIT:
      - 0.05
    CLAY:
      - 0.49
    COAL:
      - 0.1
    COAL_BLOCK:
      - 2.57
    COAL_ORE:
      - 1.44
    COARSE_DIRT:
      - 1.0
    COAST_ARMOR_TRIM_SMITHING_TEMPLATE:
      - 92.03
    COBBLED_DEEPSLATE:
      - 0.03
    COBBLESTONE:
      - 0.01
    COBWEB:
      - 2.7
    COCOA_BEANS:
      - 0.1
    COD:
      - 0.14
    COMPARATOR:
      - 2.66
    COMPASS:
      - 3.0
    CONDUIT:
      - 669.69
    COOKED_BEEF:
      - 0.26
    COOKED_CHICKEN:
      - 0.03
    COOKED_MUTTON:
      - 0.03
    COOKED_PORKCHOP:
      - 0.18
    COOKIE:
      - 0.29
    COPPER_BLOCK:
      - 1.1
    COPPER_INGOT:
      - 0.1
    CORNFLOWER:
      - 1.01
    CREAKING_HEART:
      - 300.0
    CREEPER_HEAD:
      - 4000.0
    CRIMSON_NYLIUM:
      - 3.0
    CRIMSON_STEM:
      - 0.63
    CROSSBOW:
      - 8.17
    CRYING_OBSIDIAN:
      - 12.54
    CYAN_BUNDLE:
      - 0.3
    CYAN_CONCRETE:
      - 3.0
    CYAN_WOOL:
      - 0.33
    DANDELION:
      - 1.0
    DARK_OAK_LEAVES:
      - 0.1
    DARK_OAK_LOG:
      - 0.21
    DARK_PRISMARINE:
      - 1.18
    DAYLIGHT_DETECTOR:
      - 4.2
    DEAD_BUSH:
      - 1.99
    DEEPSLATE:
      - 0.12
    DEEPSLATE_COAL_ORE:
      - 50.97
    DEEPSLATE_DIAMOND_ORE:
      - 7.62
    DEEPSLATE_EMERALD_ORE:
      - 1500.0
    DEEPSLATE_GOLD_ORE:
      - 5.0
    DEEPSLATE_IRON_ORE:
      - 5.0
    DEEPSLATE_LAPIS_ORE:
      - 4.0
    DEEPSLATE_REDSTONE_ORE:
      - 2.0
    DETECTOR_RAIL:
      - 6.0
    DIAMOND:
      - 2.64
    DIAMOND_AXE:
      - 5.14
    DIAMOND_BLOCK:
      - 18.03
    DIAMOND_BOOTS:
      - 1.5
    DIAMOND_CHESTPLATE:
      - 4.77
    DIAMOND_HELMET:
      - 2.5
    DIAMOND_HOE:
      - 9.0
    DIAMOND_HORSE_ARMOR:
      - 100.0
    DIAMOND_LEGGINGS:
      - 14.0
    DIAMOND_ORE:
      - 1.0
    DIAMOND_PICKAXE:
      - 6.39
    DIAMOND_SHOVEL:
      - 0.7
    DIAMOND_SWORD:
      - 4.73
    DIORITE:
      - 0.1
    DIRT:
      - 0.07
    DISPENSER:
      - 8.36
    DRAGON_BREATH:
      - 100.0
    DRAGON_HEAD:
      - 261.31
    DRIED_KELP:
      - 0.7
    DRIPSTONE_BLOCK:
      - 0.48
    DROPPER:
      - 5.12
    DUNE_ARMOR_TRIM_SMITHING_TEMPLATE:
      - 90.0
    EGG:
      - 0.02
    ELYTRA:
      - 2173.75
    EMERALD:
      - 0.86
    ENCHANTED_BOOK:
      - 31.94
    ENCHANTED_GOLDEN_APPLE:
      - 170.61
    ENCHANTING_TABLE:
      - 20.0
    ENDER_CHEST:
      - 25.0
    ENDER_PEARL:
      - 0.02
    END_CRYSTAL:
      - 15.0
    END_ROD:
      - 5.23
    END_STONE:
      - 0.2
    EXPERIENCE_BOTTLE:
      - 20.0
    EYE_ARMOR_TRIM_SMITHING_TEMPLATE:
      - 130.91
    FEATHER:
      - 0.24
    FERN:
      - 0.30
    FILLED_MAP:
      - 0.01
    FIREWORK_ROCKET:
      - 0.16
    FIRE_CHARGE:
      - 10.0
    FIRE_CORAL_FAN:
      - 0.75
    FISHING_ROD:
      - 0.3
    FLINT:
      - 0.01
    FLOWERING_AZALEA:
      - 2.55
    FLOWERING_AZALEA_LEAVES:
      - 0.38
    FLOWER_POT:
      - 10.5
    FLOW_ARMOR_TRIM_SMITHING_TEMPLATE:
      - 24.93
    FLOW_BANNER_PATTERN:
      - 35.0
    GHAST_TEAR:
      - 8.08
    GILDED_BLACKSTONE:
      - 4.6
    GLASS:
      - 0.19
    GLASS_BOTTLE:
      - 0.07
    GLISTERING_MELON_SLICE:
      - 0.68
    GLOWSTONE:
      - 2.52
    GLOWSTONE_DUST:
      - 0.2
    GLOW_BERRIES:
      - 5.25
    GLOW_INK_SAC:
      - 0.46
    GLOW_LICHEN:
      - 1.0
    GOAT_HORN:
      - 218.75
    GOLDEN_APPLE:
      - 11.74
    GOLDEN_CARROT:
      - 0.45
    GOLDEN_HORSE_ARMOR:
      - 15.0
    GOLD_BLOCK:
      - 3.97
    GOLD_INGOT:
      - 0.95
    GOLD_NUGGET:
      - 0.01
    GRANITE:
      - 0.15
    GRASS_BLOCK:
      - 0.21
    GRAVEL:
      - 0.12
    GRAY_CONCRETE:
      - 2.89
    GRAY_CONCRETE_POWDER:
      - 0.15
    GRAY_WOOL:
      - 0.06
    GREEN_CONCRETE:
      - 1.5
    GREEN_DYE:
      - 0.37
    GREEN_TERRACOTTA:
      - 1.75
    GREEN_WOOL:
      - 0.05
    GUNPOWDER:
      - 0.19
    HANGING_ROOTS:
      - 1.5
    HAY_BLOCK:
      - 2.49
    HEART_OF_THE_SEA:
      - 200.0
    HEAVY_CORE:
      - 654.28
    HONEYCOMB:
      - 0.01
    HONEYCOMB_BLOCK:
      - 0.22
    HONEY_BLOCK:
      - 1.75
    HOPPER:
      - 5.26
    HORN_CORAL_FAN:
      - 2.65
    ICE:
      - 1.5
    INK_SAC:
      - 1.82
    IRON_BLOCK:
      - 0.61
    IRON_HORSE_ARMOR:
      - 15.0
    IRON_INGOT:
      - 0.48
    IRON_NUGGET:
      - 1.08
    IRON_PICKAXE:
      - 1.5
    IRON_SWORD:
      - 1.0
    ITEM_FRAME:
      - 10.0
    JUKEBOX:
      - 5.0
    JUNGLE_LOG:
      - 2.05
    KELP:
      - 0.37
    LANTERN:
      - 0.19
    LAPIS_BLOCK:
      - 12.0
    LAPIS_LAZULI:
      - 0.17
    LARGE_FERN:
      - 2.5
    LAVA_BUCKET:
      - 0.38
    LEAD:
      - 2.86
    LEATHER:
      - 0.39
    LIGHT_BLUE_CONCRETE:
      - 1.5
    LIGHT_BLUE_TERRACOTTA:
      - 2.3
    LIGHT_BLUE_WOOL:
      - 0.05
    LIGHT_GRAY_CONCRETE:
      - 0.98
    LIGHT_GRAY_DYE:
      - 0.5
    LIGHT_GRAY_TERRACOTTA:
      - 2.46
    LIGHT_GRAY_WOOL:
      - 0.18
    LILAC:
      - 1.15
    LILY_OF_THE_VALLEY:
      - 1.01
    LILY_PAD:
      - 4.0
    LIME_CONCRETE:
      - 1.5
    LIME_DYE:
      - 0.05
    LIME_TERRACOTTA:
      - 1.93
    LIME_WOOL:
      - 0.06
    LODESTONE:
      - 50.0
    MACE:
      - 727.84
    MAGENTA_DYE:
      - 0.08
    MAGENTA_TERRACOTTA:
      - 1.75
    MAGENTA_WOOL:
      - 0.06
    MAGMA_BLOCK:
      - 0.26
    MANGROVE_BUTTON:
      - 0.01
    MANGROVE_LOG:
      - 1.12
    MANGROVE_PROPAGULE:
      - 0.55
    MANGROVE_ROOTS:
      - 0.8
    MEDIUM_AMETHYST_BUD:
      - 2.5
    MELON:
      - 0.1
    MELON_SLICE:
      - 0.02
    MILK_BUCKET:
      - 4.0
    MINECART:
      - 6.0
    MOSSY_COBBLESTONE:
      - 4.0
    MOSS_BLOCK:
      - 0.01
    MOSS_CARPET:
      - 0.01
    MUD:
      - 0.5
    MUD_BRICKS:
      - 1.2
    MUSHROOM_STEM:
      - 7.0
    MUSIC_DISC_11:
      - 50.0
    MUSIC_DISC_13:
      - 10.0
    MUSIC_DISC_BLOCKS:
      - 50.0
    MUSIC_DISC_CAT:
      - 5.9
    MUSIC_DISC_CHIRP:
      - 50.0
    MUSIC_DISC_CREATOR:
      - 132.86
    MUSIC_DISC_CREATOR_MUSIC_BOX:
      - 220.0
    MUSIC_DISC_FAR:
      - 0.1
    MUSIC_DISC_MALL:
      - 50.0
    MUSIC_DISC_MELLOHI:
      - 50.0
    MUSIC_DISC_OTHERSIDE:
      - 455.99
    MUSIC_DISC_PIGSTEP:
      - 200.0
    MUSIC_DISC_PRECIPICE:
      - 1066.67
    MUSIC_DISC_RELIC:
      - 4500.0
    MUSIC_DISC_STAL:
      - 50.0
    MUSIC_DISC_STRAD:
      - 50.0
    MUSIC_DISC_WAIT:
      - 50.0
    MUSIC_DISC_WARD:
      - 50.0
    MYCELIUM:
      - 0.01
    NAME_TAG:
      - 30.00
    NETHERITE_BOOTS:
      - 60.0
    NETHERITE_CHESTPLATE:
      - 60.0
    NETHERITE_HELMET:
      - 60.67
    NETHERITE_INGOT:
      - 60.91
    NETHERITE_LEGGINGS:
      - 60.0
    NETHERITE_PICKAXE:
      - 60.0
    NETHERITE_SCRAP:
      - 60.48
    NETHERITE_SWORD:
      - 60.0
    NETHERITE_UPGRADE_SMITHING_TEMPLATE:
      - 48.82
    NETHERRACK:
      - 0.19
    NETHER_BRICK:
      - 0.1
    NETHER_BRICKS:
      - 0.5
    NETHER_GOLD_ORE:
      - 0.6
    NETHER_QUARTZ_ORE:
      - 0.21
    NETHER_STAR:
      - 100.6
    NETHER_WART:
      - 0.2
    NETHER_WART_BLOCK:
      - 0.25
    OAK_LEAVES:
      - 0.05
    OAK_LOG:
      - 0.35
    OAK_PLANKS:
      - 0.64
    OAK_SAPLING:
      - 0.5
    OBSERVER:
      - 14.0
    OBSIDIAN:
      - 1.88
    OCHRE_FROGLIGHT:
      - 1.01
    OMINOUS_BOTTLE:
      - 45.36
    OMINOUS_TRIAL_KEY:
      - 68.46
    ORANGE_CONCRETE:
      - 1.5
    ORANGE_DYE:
      - 0.2
    ORANGE_TERRACOTTA:
      - 2.16
    ORANGE_TULIP:
      - 1.0
    ORANGE_WOOL:
      - 0.07
    OXEYE_DAISY:
      - 2.03
    PACKED_ICE:
      - 0.25
    PACKED_MUD:
      - 0.8
    PALE_MOSS_BLOCK:
      - 0.1
    PALE_MOSS_CARPET:
      - 0.15
    PALE_OAK_LOG:
      - 0.13
    PALE_OAK_SAPLING:
      - 0.1
    PAPER:
      - 0.33
    PEARLESCENT_FROGLIGHT:
      - 1.0
    PEONY:
      - 1.33
    PHANTOM_MEMBRANE:
      - 61.05
    PINK_BANNER:
      - 10.0
    PINK_CANDLE:
      - 10.0
    PINK_CONCRETE:
      - 3.0
    PINK_DYE:
      - 0.75
    PINK_PETALS:
      - 0.1
    PINK_TERRACOTTA:
      - 2.25
    PINK_TULIP:
      - 0.9
    PINK_WOOL:
      - 0.18
    PISTON:
      - 5.43
    PITCHER_PLANT:
      - 10.0
    PITCHER_POD:
      - 0.01
    PODZOL:
      - 1.04
    POINTED_DRIPSTONE:
      - 0.15
    POPPY:
      - 0.34
    PORKCHOP:
      - 2.1
    POTATO:
      - 0.22
    POTION:
      - 7.77
    POWDER_SNOW_BUCKET:
      - 50.0
    POWERED_RAIL:
      - 0.43
    PRISMARINE:
      - 0.06
    PRISMARINE_BRICKS:
      - 0.28
    PRISMARINE_CRYSTALS:
      - 0.24
    PRISMARINE_SHARD:
      - 0.08
    PUFFERFISH:
      - 12.0
    PUMPKIN:
      - 0.1
    PUMPKIN_PIE:
      - 0.5
    PURPLE_BANNER:
      - 10.0
    PURPLE_BED:
      - 1.0
    PURPLE_CONCRETE:
      - 1.58
    PURPLE_DYE:
      - 1.75
    PURPLE_TERRACOTTA:
      - 2.12
    PURPLE_WOOL:
      - 0.05
    PURPUR_BLOCK:
      - 1.0
    QUARTZ:
      - 0.26
    QUARTZ_BLOCK:
      - 0.62
    QUARTZ_BRICKS:
      - 0.78
    QUARTZ_STAIRS:
      - 0.9
    RABBIT_FOOT:
      - 15.0
    RABBIT_STEW:
      - 5.6
    RAIL:
      - 4.96
    RAISER_ARMOR_TRIM_SMITHING_TEMPLATE:
      - 240.0
    RAW_COPPER:
      - 0.23
    RAW_GOLD:
      - 1.99
    RAW_IRON:
      - 0.45
    RAW_IRON_BLOCK:
      - 1.16
    REDSTONE:
      - 0.32
    REDSTONE_BLOCK:
      - 2.07
    REDSTONE_LAMP:
      - 4.89
    REDSTONE_TORCH:
      - 1.05
    RED_BANNER:
      - 16.6
    RED_CONCRETE:
      - 1.5
    RED_DYE:
      - 0.03
    RED_MUSHROOM:
      - 1.21
    RED_MUSHROOM_BLOCK:
      - 0.6
    RED_SAND:
      - 1.7
    RED_TERRACOTTA:
      - 2.01
    RED_TULIP:
      - 1.03
    RED_WOOL:
      - 0.32
    REPEATER:
      - 4.12
    RESIN_BRICKS:
      - 1.5
    RESIN_CLUMP:
      - 0.59
    RIB_ARMOR_TRIM_SMITHING_TEMPLATE:
      - 127.5
    ROOTED_DIRT:
      - 0.01
    ROSE_BUSH:
      - 0.77
    ROTTEN_FLESH:
      - 0.09
    SADDLE:
      - 0.33
    SALMON:
      - 2.1
    SAND:
      - 0.09
    SANDSTONE:
      - 0.2
    SCAFFOLDING:
      - 0.06
    SCULK:
      - 0.04
    SCULK_SENSOR:
      - 3.87
    SCULK_SHRIEKER:
      - 5.0
    SCULK_VEIN:
      - 0.1
    SEAGRASS:
      - 0.1
    SEA_LANTERN:
      - 1.36
    SEA_PICKLE:
      - 2.0
    SENTRY_ARMOR_TRIM_SMITHING_TEMPLATE:
      - 119.0
    SHEARS:
      - 2.0
    SHIELD:
      - 40.0
    SHROOMLIGHT:
      - 0.25
    SHULKER_BOX:
      - 5.0
    SHULKER_SHELL:
      - 2.0
    SILENCE_ARMOR_TRIM_SMITHING_TEMPLATE:
      - 123.93
    SKELETON_SKULL:
      - 50.0
    SLIME_BALL:
      - 0.05
    SLIME_BLOCK:
      - 2.06
    SMALL_DRIPLEAF:
      - 2.43
    SMOKER:
      - 5.0
    SMOOTH_BASALT:
      - 0.2
    SMOOTH_SANDSTONE:
      - 1.0
    SMOOTH_STONE:
      - 0.12
    SNIFFER_EGG:
      - 93.83
    SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE:
      - 110.0
    SNOWBALL:
      - 5.0
    SNOW_BLOCK:
      - 0.51
    SOUL_CAMPFIRE:
      - 2.0
    SOUL_LANTERN:
      - 0.36
    SOUL_SAND:
      - 1.45
    SOUL_SOIL:
      - 1.74
    SPIDER_EYE:
      - 0.02
    SPIRE_ARMOR_TRIM_SMITHING_TEMPLATE:
      - 159.0
    SPLASH_POTION:
      - 9.94
    SPONGE:
      - 18.6
    SPORE_BLOSSOM:
      - 9.24
    SPRUCE_LEAVES:
      - 0.5
    SPRUCE_LOG:
      - 0.13
    SPYGLASS:
      - 40.0
    STICK:
      - 0.01
    STICKY_PISTON:
      - 17.48
    STONE:
      - 0.04
    STONE_BRICKS:
      - 0.04
    STRING:
      - 0.24
    SUGAR:
      - 1.16
    SUGAR_CANE:
      - 0.04
    SUNFLOWER:
      - 0.78
    SUSPICIOUS_GRAVEL:
      - 50.0
    SUSPICIOUS_SAND:
      - 50.0
    SWEET_BERRIES:
      - 0.18
    TADPOLE_BUCKET:
      - 2.0
    TERRACOTTA:
      - 0.3
    TIDE_ARMOR_TRIM_SMITHING_TEMPLATE:
      - 173.33
    TINTED_GLASS:
      - 0.5
    TIPPED_ARROW:
      - 5.94
    TNT:
      - 4.07
    TORCH:
      - 1.25
    TORCHFLOWER:
      - 10.0
    TORCHFLOWER_SEEDS:
      - 0.01
    TOTEM_OF_UNDYING:
      - 939.0
    TRIAL_KEY:
      - 3.86
    TRIDENT:
      - 653.23
    TRIPWIRE_HOOK:
      - 7.0
    TROPICAL_FISH:
      - 2.1
    TROPICAL_FISH_BUCKET:
      - 13.41
    TUBE_CORAL_FAN:
      - 0.75
    TUFF:
      - 0.11
    TUFF_BRICKS:
      - 0.12
    TURTLE_EGG:
      - 13.71
    TURTLE_HELMET:
      - 53.62
    TURTLE_SCUTE:
      - 36.25
    TWISTING_VINES:
      - 2.5
    VERDANT_FROGLIGHT:
      - 1.02
    VEX_ARMOR_TRIM_SMITHING_TEMPLATE:
      - 242.0
    VINE:
      - 1.78
    WARD_ARMOR_TRIM_SMITHING_TEMPLATE:
      - 80.92
    WARPED_NYLIUM:
      - 3.0
    WARPED_ROOTS:
      - 0.2
    WARPED_STEM:
      - 0.6
    WAXED_COPPER_BLOCK:
      - 1.0
    WAXED_COPPER_BULB:
      - 25.0
    WAXED_OXIDIZED_COPPER:
      - 1.0
    WAYFINDER_ARMOR_TRIM_SMITHING_TEMPLATE:
      - 110.0
    WEEPING_VINES:
      - 2.5
    WHEAT:
      - 0.16
    WHEAT_SEEDS:
      - 0.01
    WHITE_BANNER:
      - 8.71
    WHITE_CONCRETE:
      - 2.19
    WHITE_DYE:
      - 0.05
    WHITE_TERRACOTTA:
      - 1.06
    WHITE_TULIP:
      - 1.0
    WHITE_WOOL:
      - 0.08
    WILD_ARMOR_TRIM_SMITHING_TEMPLATE:
      - 101.25
    WIND_CHARGE:
      - 0.48
    WITHER_ROSE:
      - 0.62
    WITHER_SKELETON_SKULL:
      - 26.79
    WOLF_ARMOR:
      - 3.02
    WRITABLE_BOOK:
      - 40.0
    YELLOW_CONCRETE:
      - 1.99
    YELLOW_DYE:
      - 0.4
    YELLOW_TERRACOTTA:
      - 2.65
    YELLOW_WOOL:
      - 0.13
