shop-title: "Shop Listings"

previous-page-text: "&7Previous Page"
previous-page-item: "ARROW"
next-page-text: "&7Next Page"
next-page-item: "ARROW"

shop-guide-text: "&7Shop Guide"
shop-guide-item: "WRITABLE_BOOK"
shop-guide-info:
  - '&b/finditem'
  - '&fThis will open the shop menu'
  - '&fand show all items.'
  - ''
  - '&b/finditem ENCHANTED_BOOK'
  - '&fThis will find shops with'
  - '&fenchanted books.'
  - ''
  - '&b/finditem ENCHANTED_BOOK fortune'
  - '&fThis will find shops with'
  - '&fenchanted books that contains'
  - '&fthe text "fortune".'
  - ''
  - '&b/finditem voting item'
  - '&fThis will find all items containing'
  - '&fthe word "voting item".'

shop-type-guide-text: "&7Shop Type"
shop-type-guide-item: "COMPARATOR"

# Randomize the listings each time a user does /finditem
# instead of being ordered each time by date.
randomize-listing: true